version: '3.9'

services:
  django:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - database
      - redis
    networks:
      - djangonetwork
  
  database:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    container_name: database
    ports:
      - '5432:5432'
    networks:
      - djangonetwork
  
  redis:
    image: redis:7.4.1
    hostname: redis
    ports:
      - '6379:6379'
    networks:
      - djangonetwork


networks:
  djangonetwork:
    driver: bridge