version: '3.9'

services:
  web:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    environment:
      - DB_HOST=database
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=pass
    command: ['./start.sh']
    depends_on:
      - database
      - redis
  
  database:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
  
  redis:
    image: redis:7.4.1
    hostname: redis
    ports:
      - "6379:6379"