# Generated by Django 5.1.2 on 2024-11-11 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_companyinvitation_status'),
        ('users', '0004_userrequest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrequest',
            unique_together={('company', 'sender')},
        ),
    ]
