# Generated by Django 5.1.2 on 2024-11-12 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userrequest_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrequest',
            options={'verbose_name_plural': 'User Requests'},
        ),
    ]
