# Generated by Django 5.1.2 on 2024-11-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_companyinvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinvitation',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('D', 'Declined'), ('R', 'Revoked')], default='P', max_length=1),
        ),
    ]
