# Generated by Django 5.1.2 on 2024-11-12 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_companyinvitation_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyinvitation',
            options={'verbose_name_plural': 'Company Invitations'},
        ),
    ]
