name: EC2 Deployment

on:
  pull_request:
    types:
      - closed

jobs:
  deploy:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'develop'
    name: Deploy to EC2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build & Deploy
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{secrets.SSH_HOST}}
          USER_NAME: ${{secrets.USER_NAME}}
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
        
        run: |
          echo $PRIVATE_KEY | tr ' ' '\n' | base64 --decode > key.pem
          chmod 400 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem ${USER_NAME}@${HOSTNAME} '
            cd backend-medduzen-internship && 
            sudo chmod +x start.sh &&
            eval "$(ssh-agent -s)" &&
            ssh-add ~/.ssh/key1 &&
            git checkout ${BRANCH_NAME} &&
            git fetch --all &&
            git pull origin ${BRANCH_NAME} &&
            sudo chmod +x start.sh &&
            sudo docker-compose up -d --build
          '
          