name: Django CI
on:
  push:
  pull_request:
  workflow_call:

jobs:
  django:
    name: django
    runs-on: ubuntu-latest
    container: python:3.11-slim

    services:
      postgres:
        image: postgres:13
        env_file:
          - .env
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U $POSTGRES_USER" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations check
        run: |
          python3 manage.py makemigrations --check --dry-run
        
      - name: Run linting
        run: |
          ruff check .

      - name: Run tests
        run: |
          python3 manage.py migrate
          python3 manage.py test backend.apps.users.tests
